services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: word
      MYSQL_DATABASE: wordpresssitedb
      
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: word
      WORDPRESS_DB_NAME: wordpresssitedb
    volumes:
      - ./wordpress:/var/www/html

  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "80:80"
